### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by AlanApter** [yoe/fdpowermon#1]
where is the AUR package? thanks!

**Comment by yoe** [comment]
Apparently they removed it. I'm not an arch user myself, so can't help you with how to get it back (if at all).

You'll need to talk to the arch people if you want to get it to be packaged again

Alternatively, since it's just a perl script anyway, you can also just get the tarball and do it that way. You'll have a bit more manual work that way, though.

**Comment by AlanApter** [comment]
Ah, that's a pity.

Thanks for the quick response.
