### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by aario** [yoe/fdpowermon#2]
Thanks. But it doesn't work. I mean no error message on terminal execution. It just doesn't appear on the system tray. I wish I could provide more info but there is no log or stderr output.
Debian stretch
Installed the package on debian repos.

**Comment by yoe** [comment]
For bugs in Debian, please check out the Debian BTS at bugs.debian.org (and the 'reportbug' package).

This is very likely just bug [823732](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823732). Please check that out for more details; if that doesn't fix it, you can use `reportbug` to follow up

Closing, since this is probably not a bug ;-)

**Comment by aario** [comment]
Well thanks for addressing this. Yes. At the time of testing my battery was 100% fully charged. So that might be the bug report I'm looking for.
