### ISSUE TITLE
Recent kernel patch causes error when not charging.

### ISSUE THREAD

**Issue by replica9000** [yoe/fdpowermon#3]
A recent change in kernel 5.16.3, /drivers/acpi/battery.c causes fdpowermon to not load/update when on AC but not charging, giving this error:
`Use of uninitialized value $level in multiplication (*) at /usr/bin/fdpowermon line 439, <$acpi> line 2`

[battery.c-5.16.3.patch.txt](https://github.com/yoe/fdpowermon/files/7966863/battery.c-5.16.3.patch.txt)

**Comment by J-Reis** [comment]
In case it helps, I'm also seeing this.
```Use of uninitialized value $level in multiplication (*) at /usr/bin/fdpowermon line 439, <$acpi> line 2.```
Debian 10, kernel: 4.19.0-19-amd64. Timing seems right for that to be the same kernel patch.

**Comment by J-Reis** [comment]
There's a patch proposed here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007702

In incredibly slap-dash, un-thorough testing it does work for me.

The Debian maintainer addressed appears to be the same as the owner of this repo so I'm just posting here in case it helps someone passing by. I'm out of my depth, otherwise. Please forgive.

**Comment by replica9000** [comment]
Thanks for pointing out the patch.  I re-packed the official deb with the patched file. Seems to be working well for me too.

[fdpowermon_1.19-jcg1_all.deb.zip](https://github.com/yoe/fdpowermon/files/8327273/fdpowermon_1.19-jcg1_all.deb.zip)
